
#!/bin/bash	1.md	corridor.md
cd md 
mv	2.md	pride.md
mv	3.md	deepl.md
mv	4.md	parish.md
mv	5.md	workings.md
mv	6.md	postgis.md
mv	8.md	influxdb.md
mv	9.md	van.md
mv	10.md	qgis.md
mv	11.md	unzip-sh.md
mv	12.md	clamp.md
mv	13.md	vscode.md
mv	14.md	pudding.md
mv	15.md	aonb.md
mv	16.md	least-cost-path.md
mv	17.md	microclimates.md
mv	18.md	rpict.md
mv	19.md	catalyst.md
mv	20.md	rclone.md
mv	21.md	saas.md
mv	22.md	parcel.md
mv	23.md	cisco.md
mv	24.md	rename-sh.md
mv	25.md	bristol-city-council.md
mv	26.md	concentrator.md
mv	27.md	lidar.md
mv	28.md	sat.md
mv	29.md	iaas.md
mv	30.md	inspire.md
mv	31.md	solar.md
mv	32.md	mastermap.md
mv	33.md	bha.md
mv	34.md	radiance.md
mv	35.md	material.md
mv	36.md	php.md
mv	37.md	network-status.md
mv	38.md	parish.md
mv	39.md	openai.md
mv	40.md	windsor.md
mv	42.md	obd.md
mv	43.md	mhz19.md
mv	44.md	coreos-pi.md
mv	45.md	fedora.md
mv	46.md	flat-terrain.md
mv	47.md	arcgis.md
mv	48.md	bash.md
mv	49.md	bha.md
mv	50.md	canbus.md
mv	51.md	sql.md
mv	52.md	ruckus.md
mv	53.md	raspberrypi.md
mv	54.md	qgis.md
mv	55.md	kvm.md
mv	56.md	python.md
mv	57.md	mqtt.md
mv	58.md	coreos.md
mv	59.md	gdal.md
mv	60.md	javascript.md
mv	61.md	mapbox.md
mv	62.md	mikrotik.md
mv	63.md	github.md
mv	64.md	grasshopper.md
mv	65.md	leaflet.md
mv	66.md	ladybug.md
mv	66.md	window.md
mv	68.md	sun.md
mv	69.md	stage.md
mv	60.md	sun.md
mv	71.md	node.md
mv	72.md	egg.md
mv	73.md	dymaxion.md
mv	74.md	egg.md
mv	75.md	egg.md
mv	76.md	podman.md